Database: vet_clinic Database
Ridwanullahi-code/vet_clinic pull request #2
Opened 2022-12-21 17:19 UTC by Ridwanullahi-code

- Create a database named vet_clinic
- Create a table named animals
- Insert the data into the animal's table
- Write queries to fetch data from the animal's table
- Create a folder to organize the output

2022-12-21 17:41 UTC, danmainah requested changes
Hi @Ridwanullahi-code , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ Gitflow was correctly used
✔️  Good design


# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-12-21 17:41 UTC, danmainah commented on schema.sql
> +    name TEXT NOT NULL,
- [ ] @Ridwanullahi-code great work on your schema however the name should have the varchar datatype to represent the string value.(NB varchar can have different length specified according to you)

2022-12-21 17:41 UTC, danmainah commented on data.sql
> +VALUES(1, 'Augumon','2020-02-02',0,FALSE,10.23);
@Ridwanullahi-code create work inserting data into the database however your entries for date of birth and neutered are wrong kindly correct it, also consider wring all boolean values in small letters.

2022-12-21 17:41 UTC, danmainah commented on data.sql
> +VALUES(4, 'Devimon','2017-05-12',5,TRUE,10.23);
- [ ] @Ridwanullahi-code create work inserting data into the database however your entries for weight is wrong kindly correct it,

2022-12-21 17:41 UTC, danmainah commented on queries.sql
> +WHERE weight_kg = 10.4 OR weight_kg <= 17.3
- [ ] @Ridwanullahi-code great work on your queries, however, you forgot to include the screenshot of the queries in your pull request description kindly edit the description and add them, this is a project requirement
![image](https://user-images.githubusercontent.com/61408860/208969481-0ffec967-ebec-4926-9134-9c0f7abcf74e.png)

2022-12-22 00:02 UTC, Gambit142 requested changes
Hi @Ridwanullahi-code 👋, 

Great work on making the changes requested by a previous reviewer 👏 

## Highlights
- All codes for creating, structuring and altering tables are in the _**schema.sql**_ file ✔️ 
- All codes that populate tables with data are in the _**data.sql**_ file ✔️ 
- All codes that query or help to analyze data are in the _**queries.sql**_ file ✔️ 

You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

 ## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- Kindly check the comments tagged [OPTIONAL]

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please, remember to tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-22 00:02 UTC, Gambit142 commented on data.sql
> +VALUES(4, 'Devimon','12/05/2017',5,true,11.0);
- [ ] Nice work inserting data for the `animals` table based on the recommendation of the first reviewer. However, the code change produces this error when I run this file

![image](https://user-images.githubusercontent.com/77106962/209024162-c280b6c3-f543-447e-b8eb-d9f3ba6c48f6.png)

This has to do with the format of the `datestyle(day/month/year)` you use which is different from the default format in Postgresql configuration. To solve this, kindly add this line of code to the top of this file `SET datestyle = dmy;`

2022-12-22 00:02 UTC, Gambit142 commented on queries.sql
> +
- [ OPTIONAL] The query states that you should list the `name` and `escape attempt` not just the name. It would be nice to implement it as required. 👍

2022-12-22 00:02 UTC, Gambit142 commented on queries.sql
> +WHERE weight_kg = 10.4 OR weight_kg <= 17.3
- [ OPTIONAL] The result of this query is wrong. The query states that you should find all animals between the weight of 10.4 kg and 17.3kg. That means you want to get those weights that are `>= 10.4 AND <=17.3`. It would be nice to correct this query, return the correct result and update the screenshot. 👍

2022-12-22 10:29 UTC, 1GORDON approved these changes
# Status: APPROVED 🟢 

Hi @Ridwanullahi-code ✋

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! :tada: :clap: :clap: :100:

## Highlights!
- Followed Gitflow ✔️
- Good commit messages ✔️
- Descriptive Pull request ✔️
- Professional readme ✔️

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-22 21:06 UTC, closed without merging